### ISSUE TITLE
Refactor contract.getPastEvents

### ISSUE THREAD

**Issue by niklr** [vitelabs/vuilder#16]
The current implementation of `contract.getPastEvents` works well to receive all events but is not very efficient when filtering by a specific event. It basically fetches all events from the RPC and then filters them locally. This can be avoided by including the filter in the request itself. Additionally, it is currently not possible to filter by indexed values.

Refactor suggestions:

Before:
```typescript
getPastEvents(eventName: string = 'allEvents', {fromHeight = 0, toHeight = 0}:{
    filter?: Object,
    fromHeight?: Number,
    toHeight?: Number
  }) {
```

After:
```typescript
getAllPastEvents(fromHeight: number = 0, toHeight: number = 0) {
```
-> Different interface (breaking change) but same implementation as before.

New:
```typescript
getPastEvents(eventName: string, fromHeight: number = 0, toHeight: number = 0, filter?: [null | { type: string, value: string }]) {
```

The filter has to be an array but can contain null objects. Null objects are needed to skip a specific indexed value (the order is important and has to be maintained). The filter could then look like this:

```typescript
[
  null,
  {
    type: "uint256",
    value: "1234"
  }
]
```

**Comment by viteshan** [comment]
This is a nice refactoring. we can use topics to get a specific event.(event name or indexed value)

https://docs.vite.org/vite-docs/api/rpc/ledger_v2.html#ledger-getvmlogsbyfilter

**Comment by niklr** [comment]
Implement similar to:

- https://web3js.readthedocs.io/en/v1.7.3/web3-eth-contract.html#getpastevents
- https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-eth-contract/src/index.js
